version: '2'

services:
  flask:
    build: .
    image: microblog:latest
    restart: always
    ports: 
      - "5000"
    env_file:
      - variables.env
    networks:
      - app-network
    depends_on:
      - dbserver

  dbserver:
    image: mysql/mysql-server:latest
    container_name: dbserver
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=password
    volumes:
      - data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl
    depends_on:
      - flask
    networks:
      - app-network
    restart: always

volumes:
  data:

networks:
  app-network: